"""add_reid_columns

Revision ID: 55cbfd5b356a
Revises: ffb7e58f783e
Create Date: 2026-04-03 10:00:45.150445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cbfd5b356a'
down_revision: Union[str, Sequence[str], None] = 'ffb7e58f783e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('incidents', sa.Column('appearance_id', sa.String(length=20), nullable=True))
    # SQLite cannot add a NOT NULL Boolean with no server-default to an existing table,
    # so add as nullable then back-fill to False for all existing rows.
    op.add_column('incidents', sa.Column('is_repeat_visitor', sa.Boolean(), nullable=True))
    op.execute("UPDATE incidents SET is_repeat_visitor = 0 WHERE is_repeat_visitor IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'is_repeat_visitor')
    op.drop_column('incidents', 'appearance_id')
    # ### end Alembic commands ###
