"""add_is_repeat_visitor

Revision ID: ab46a5b786f1
Revises: 55cbfd5b356a
Create Date: 2026-04-03 10:03:53.191723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab46a5b786f1'
down_revision: Union[str, Sequence[str], None] = '55cbfd5b356a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('incidents', sa.Column('is_repeat_visitor', sa.Boolean(), nullable=True))
    op.execute("UPDATE incidents SET is_repeat_visitor = 0 WHERE is_repeat_visitor IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'is_repeat_visitor')
    # ### end Alembic commands ###
